// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeuYXC-IX8GT8m7fvwLrJ4RmbkUteZoWk',
    appId: '1:986502768462:web:111cd71b33888a3bc7e01f',
    messagingSenderId: '986502768462',
    projectId: 'agenda-43f45',
    authDomain: 'agenda-43f45.firebaseapp.com',
    storageBucket: 'agenda-43f45.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAuwZ6GC3lb-N8fQkEnY-FCijtcaPxIR8',
    appId: '1:986502768462:android:c5b8835739d054c5c7e01f',
    messagingSenderId: '986502768462',
    projectId: 'agenda-43f45',
    storageBucket: 'agenda-43f45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqVumSpMyj3o0S-xRLJSh1-DXvX5gIZ_8',
    appId: '1:986502768462:ios:fdf1baae649af6c0c7e01f',
    messagingSenderId: '986502768462',
    projectId: 'agenda-43f45',
    storageBucket: 'agenda-43f45.firebasestorage.app',
    iosBundleId: 'com.example.agenda',
  );
}
